import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nnavbar } from "@/components/nnavbar";
import Footer from "@/components/footer";
import Navvbar from "@/components/navvbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ fontFamily: "system-ui, sans-serif" }}
      className="min-h-full flex flex-col"
    >
      <body className="min-h-full flex flex-col">
        <Nnavbar />
        {/* <Navvbar /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
