import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nnavbar } from "@/components/nnavbar";
import Subnavbar from "@/components/subnavbar";
import Footer from "@/components/footer";
import { FooterRegulatoryTrust } from "@/components/footerregulatorytrust";
import { NavShell } from "@/components/navshell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Durapay App",
  description: "Generated by create next app",
  icons: {
    icon: "/wallet.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ fontFamily: "system-ui, sans-serif" }}
      className="min-h-full"
    >
      <body className=" w-full min-h-screen overflow-x-hidden">
        <NavShell />
        <main>{children}</main>
        <Footer />
        <FooterRegulatoryTrust />
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Nnavbar } from "@/components/nnavbar";
// import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Durapay App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="min-h-full">
//       <body className="min-h-full flex flex-col w-full overflow-x-hidden">
//         <Nnavbar />
//         <main className="flex-1 w-full">{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
